# Site settings
author: Benito Galvez
title: Making My Software Engineering Dream into a Reality
header-img: img/home-bg.png
email: mystwalker131@gmail.com
copyright_name: Benito Galvez
description: > # this means to ignore newlines until "baseurl:"
  Software Engineering school experiences
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Mystwalker131

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
